syntax = "proto3";

import "common/vector3.proto";

message S2CEntityCreate {
    uint64 id = 1;
    string name = 2;
    Vec3 pos = 3;
}

message S2CEntityDestory {
    uint64 id = 1;
}

message C2SEntityDestoryRequest {
    string uuid = 1;
    uint64 id = 2;
}

message C2SEntityCreateRequest {
    string uuid = 1;
    string name = 2;
    Vec3 pos = 3;
}

message S2CEntityUpdate {
    uint64 id = 1;
    Vec3 pos = 2;
    Vec3 direction = 3;
    int32 gait = 4;
}

message S2CEntityUpdateBatch {
    repeated S2CEntityUpdate updates = 1;
}