syntax = "proto3";
import "common/vector3.proto";
import "common/error.proto";
message LoginReq {
    bytes public_key = 1;
    bytes uuid = 2;
}

message LoginChallenge {
    bytes challenge = 1;
    bytes uuid = 2;
}

message LoginProof {
    bytes signature = 1; 
    bytes uuid = 2;
    string name = 3;
}

message LoginRsp {
    Error error = 1;
    bool voice_chat = 2;
    Vec3 pos = 3;
    float yaw = 4;
    float pitch = 5;
}

message LogoutReq {
    bytes uuid = 1;
}

message LogoutRsp {
    bytes uuid = 1;
    bool server_stop = 2;
}

